// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ProjectManagementSystem.Shared.Models
{
    public partial class DelayType
    {
        public DelayType()
        {
            Projects = new HashSet<Project>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("DelayType")]
        [StringLength(50)]
        [Unicode(false)]
        public string DelayType1 { get; set; }

        [InverseProperty("DelayTypeNavigation")]
        public virtual ICollection<Project> Projects { get; set; }
    }
}