// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ProjectManagementSystem.Shared.Models
{
    [Table("Employee")]
    public partial class Employee
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("First Name")]
        [StringLength(255)]
        public string FirstName { get; set; }
        [Required]
        [Column("Last Name")]
        [StringLength(255)]
        public string LastName { get; set; }
        [Required]
        [StringLength(450)]
        public string Role { get; set; }
        public int Gender { get; set; }
        [Column("DOB", TypeName = "date")]
        public DateTime Dob { get; set; }

        [ForeignKey("Gender")]
        [InverseProperty("Employees")]
        public virtual GenderTable GenderNavigation { get; set; }
        [ForeignKey("Role")]
        [InverseProperty("Employees")]
        public virtual AspNetRole RoleNavigation { get; set; }
    }
}