// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ProjectManagementSystem.Shared.Models
{
    [Table("GenderTable")]
    public partial class GenderTable
    {
        public GenderTable()
        {
            Employees = new HashSet<Employee>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        public string GenderType { get; set; }

        [InverseProperty("GenderNavigation")]
        public virtual ICollection<Employee> Employees { get; set; }
    }
}