// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ProjectManagementSystem.Shared.Models
{
    [Index("Use", Name = "IX_Keys_Use")]
    public partial class Key
    {
        [Key]
        public string Id { get; set; }
        public int Version { get; set; }
        public DateTime Created { get; set; }
        public string Use { get; set; }
        [Required]
        [StringLength(100)]
        public string Algorithm { get; set; }
        [Column("IsX509Certificate")]
        public bool IsX509certificate { get; set; }
        public bool DataProtected { get; set; }
        [Required]
        public string Data { get; set; }
    }
}