// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ProjectManagementSystem.Shared.Models
{
    [Table("Project")]
    public partial class Project
    {
        public Project()
        {
            CancelledProjects = new HashSet<CancelledProject>();
            CompletedProjects = new HashSet<CompletedProject>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [StringLength(255)]
        public string ProjectName { get; set; }
        [Required]
        [StringLength(255)]
        public string ProjectCode { get; set; }
        [Column(TypeName = "date")]
        public DateTime? ExpectedReleaseDate { get; set; }
        [Column(TypeName = "date")]
        public DateTime? PreProductionCompletionDate { get; set; }
        [Column(TypeName = "date")]
        public DateTime? ProductionCompletion { get; set; }
        [Column(TypeName = "date")]
        public DateTime? TestingCompletion { get; set; }
        public int LeadDev { get; set; }
        public int Status { get; set; }
        public int? ProjectType { get; set; }
        public string ProjectImage { get; set; }
        [Unicode(false)]
        public string ReasonForDelayPreProd { get; set; }
        [Unicode(false)]
        public string ReasonForDelayProd { get; set; }
        [Unicode(false)]
        public string ResonForDelayTest { get; set; }
        [Unicode(false)]
        public string ReasonForDelayrelease { get; set; }
        public int? DelayType { get; set; }
        public int? ProjectProgress { get; set; }

        [ForeignKey("DelayType")]
        [InverseProperty("Projects")]
        public virtual DelayType DelayTypeNavigation { get; set; }
        [ForeignKey("ProjectProgress")]
        [InverseProperty("Projects")]
        public virtual ProjectProgressTable ProjectProgressNavigation { get; set; }
        [ForeignKey("ProjectType")]
        [InverseProperty("Projects")]
        public virtual ProjectType ProjectTypeNavigation { get; set; }
        [ForeignKey("Status")]
        [InverseProperty("Projects")]
        public virtual Status StatusNavigation { get; set; }
        [InverseProperty("Project")]
        public virtual ICollection<CancelledProject> CancelledProjects { get; set; }
        [InverseProperty("Project")]
        public virtual ICollection<CompletedProject> CompletedProjects { get; set; }
    }
}